using System;
using System.Collections.Generic;
using System.Text;

namespace Stacklands_Randomizer_Mod
{
    public static class CustomQuestMapping
    {
        public static readonly List<Quest> Map = new()
        {
            /* ----- Additional Quests ----- */
            
            // To be added in future...

            /* ----- Mobsanity Quests ----- */

            new($"kill_{Cards.bear}")                 { OnSpecialAction = (string action) => action == $"{Cards.bear}_killed",               PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.dark_elf}")             { OnSpecialAction = (string action) => action == $"{Cards.dark_elf}_killed",           PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.elf}")                  { OnSpecialAction = (string action) => action == $"{Cards.elf}_killed",                PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.elf_archer}")           { OnSpecialAction = (string action) => action == $"{Cards.elf_archer}_killed",         PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.enchanted_shroom}")     { OnSpecialAction = (string action) => action == $"{Cards.enchanted_shroom}_killed",   PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.ent}")                  { OnSpecialAction = (string action) => action == $"{Cards.ent}_killed",                PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.feral_cat}")            { OnSpecialAction = (string action) => action == $"{Cards.feral_cat}_killed",          PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.frog_man}")             { OnSpecialAction = (string action) => action == $"{Cards.frog_man}_killed",           PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.ghost}")                { OnSpecialAction = (string action) => action == $"{Cards.ghost}_killed",              PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.giant_rat}")            { OnSpecialAction = (string action) => action == $"{Cards.giant_rat}_killed",          PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.giant_snail}")          { OnSpecialAction = (string action) => action == $"{Cards.giant_snail}_killed",        PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.goblin}")               { OnSpecialAction = (string action) => action == $"{Cards.goblin}_killed",             PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.goblin_archer}")        { OnSpecialAction = (string action) => action == $"{Cards.goblin_archer}_killed",      PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.goblin_shaman}")        { OnSpecialAction = (string action) => action == $"{Cards.goblin_shaman}_killed",      PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.merman}")               { OnSpecialAction = (string action) => action == $"{Cards.merman}_killed",             PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.mimic}")                { OnSpecialAction = (string action) => action == $"{Cards.mimic}_killed",              PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.mosquito}")             { OnSpecialAction = (string action) => action == $"{Cards.mosquito}_killed",           PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.ogre}")                 { OnSpecialAction = (string action) => action == $"{Cards.ogre}_killed",               PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.orc_wizard}")           { OnSpecialAction = (string action) => action == $"{Cards.orc_wizard}_killed",         PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.slime}")                { OnSpecialAction = (string action) => action == $"{Cards.slime}_killed",              PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.small_slime}")          { OnSpecialAction = (string action) => action == $"{Cards.small_slime}_killed",        PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.snake}")                { OnSpecialAction = (string action) => action == $"{Cards.snake}_killed",              PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.tiger}")                { OnSpecialAction = (string action) => action == $"{Cards.tiger}_killed",              PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },
            new($"kill_{Cards.wolf}")                 { OnSpecialAction = (string action) => action == $"{Cards.wolf}_killed",               PossibleInPeacefulMode = false,      QuestGroup = EnumExtensionHandler.MobsanityQuestGroupEnum },

            /* ----- Packsanity Quests ----- */

            new($"buy_idea_booster")                  { OnSpecialAction = (string action) => action == $"buy_idea_pack"                     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.PacksanityQuestGroupEnum },
            new($"buy_farming_booster")               { OnSpecialAction = (string action) => action == $"buy_farming_pack"                  , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.PacksanityQuestGroupEnum },
            new($"buy_cooking_booster")               { OnSpecialAction = (string action) => action == $"buy_cooking_pack"                  , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.PacksanityQuestGroupEnum },
            new($"buy_idea2_booster")                 { OnSpecialAction = (string action) => action == $"buy_idea2_pack"                    , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.PacksanityQuestGroupEnum },
            new($"buy_equipment_booster")             { OnSpecialAction = (string action) => action == $"buy_equipment_pack"                , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.PacksanityQuestGroupEnum },
            new($"buy_locations_booster")             { OnSpecialAction = (string action) => action == $"buy_locations_pack"                , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.PacksanityQuestGroupEnum },
            new($"buy_structures_booster")            { OnSpecialAction = (string action) => action == $"buy_structures_pack"               , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.PacksanityQuestGroupEnum },

            /* ----- Spendsanity Quests ----- */
            new("buy_1_ap_spendsanity_pack")    { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 1               , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 1 },
            new("buy_2_ap_spendsanity_pack")    { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 2               , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 2 },
            new("buy_3_ap_spendsanity_pack")    { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 3               , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 3 },
            new("buy_4_ap_spendsanity_pack")    { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 4               , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 4 },
            new("buy_5_ap_spendsanity_pack")    { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 5               , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 5 },
            new("buy_6_ap_spendsanity_pack")    { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 6               , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 6 },
            new("buy_7_ap_spendsanity_pack")    { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 7               , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 7 },
            new("buy_8_ap_spendsanity_pack")    { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 8               , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 8 },
            new("buy_9_ap_spendsanity_pack")    { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 9               , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 9 },
            new("buy_10_ap_spendsanity_pack")   { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 10              , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 10},
            new("buy_11_ap_spendsanity_pack")   { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 11              , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 11},
            new("buy_12_ap_spendsanity_pack")   { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 12              , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 12},
            new("buy_13_ap_spendsanity_pack")   { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 13              , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 13},
            new("buy_14_ap_spendsanity_pack")   { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 14              , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 14},
            new("buy_15_ap_spendsanity_pack")   { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 15              , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 15},
            new("buy_16_ap_spendsanity_pack")   { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 16              , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 16},
            new("buy_17_ap_spendsanity_pack")   { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 17              , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 17},
            new("buy_18_ap_spendsanity_pack")   { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 18              , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 18},
            new("buy_19_ap_spendsanity_pack")   { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 19              , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 19},
            new("buy_20_ap_spendsanity_pack")   { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 20              , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 20},
            new("buy_21_ap_spendsanity_pack")   { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 21              , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 21},
            new("buy_22_ap_spendsanity_pack")   { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 22              , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 22},
            new("buy_23_ap_spendsanity_pack")   { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 23              , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 23},
            new("buy_24_ap_spendsanity_pack")   { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 24              , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 24},
            new("buy_25_ap_spendsanity_pack")   { OnSpecialAction = (string action) => action == $"buy_{ModBoosterPacks.spendsanity}_pack" && CommonPatchMethods.GetTimesBoosterPackBought(ModBoosterPacks.spendsanity) >= 25              , DescriptionTermOverride = ModTerms.SpendsanityQuestDescription     , PossibleInPeacefulMode = true      , QuestGroup = EnumExtensionHandler.SpendsanityQuestGroupEnum      , RequiredCount = 25},
        };
    }
}
